conv_gem = "models/yeast-GEM.xml"
org_name = "Saccharomyces cerevisiae"
sigma = 0.5
p_tot = 0.5
f = 0.4461
gr_exp = 0.41

[kegg]
id = "sce"

[uniprot]
id = "559292"
reviewed = false

[complex]
taxonomic_id = 559292